export const PLUGIN_KEY = "plugin-filesystem";
export const LUCID_VERSION = "0.x.x";
export const DEFAULT_UPLOAD_DIRECTORY = "uploads";
export const FILE_SYSTEM_UPLOAD_PATH = "fs/upload";
export const FILE_SYSTEM_DOWNLOAD_PATH = "fs/download";
export const FILE_SYSTEM_UPLOAD_ROUTE = `/lucid/api/v1/${FILE_SYSTEM_UPLOAD_PATH}`;
export const FILE_SYSTEM_DOWNLOAD_ROUTE = `/lucid/api/v1/${FILE_SYSTEM_DOWNLOAD_PATH}`;
export const FILE_SYSTEM_RATE_LIMIT = 20;
export const FILE_SYSTEM_RATE_LIMIT_WINDOW_MS = 60 * 1000;
