import { type AccessConfig, getCapabilityRegistry } from "./capabilities.js";
import { Permissions } from "./definitions.js";
import type {
	CorePermission,
	Permission,
	PermissionGroup,
	StaticPermission,
} from "./types.js";

export const corePermissionKeys = Object.values(
	Permissions,
) as StaticPermission[];

const collectionPermissionRegex =
	/^documents:[a-z0-9-_]+:(read|create|create-request|update|delete|restore|publish|review)$/;
const agentPermissionRegex =
	/^agents:[a-z0-9-]+:(chat|manage-own-routines|manage-code-routines)$/;

/** Checks whether a permission is owned and generated by Lucid. */
export const isCorePermission = (
	permission: string,
): permission is CorePermission => {
	return (
		corePermissionKeys.some((key) => key === permission) ||
		collectionPermissionRegex.test(permission) ||
		agentPermissionRegex.test(permission)
	);
};

/** Builds the core, collection and custom permission catalogue. */
export const getPermissionRegistry = (
	config: AccessConfig,
): PermissionGroup[] => {
	return getCapabilityRegistry(config)
		.map(
			(group): PermissionGroup => ({
				key: group.key,
				details: group.details,
				core: group.core,
				permissions: group.capabilities.flatMap((capability) =>
					capability.permission === undefined
						? []
						: [
								{
									key: capability.permission,
									details: capability.details,
									core: capability.core,
								},
							],
				),
			}),
		)
		.filter((group) => group.permissions.length > 0);
};

const permissionGroupOrder = new Map(
	[
		"documents",
		"media_permissions",
		"request_permissions",
		"agents",
		"ai_permissions",
		"users_permissions",
		"roles_permissions",
		"integrations_permissions",
		"emails_permissions",
		"jobs_permissions",
		"settings_permissions",
	].map((key, index) => [key, index]),
);

const permissionActionOrder = new Map(
	[
		"read",
		"read-all",
		"chat",
		"create",
		"create-request",
		"manage-own-routines",
		"manage-code-routines",
		"update",
		"restore",
		"review",
		"publish",
		"send",
		"regenerate",
		"manage",
		"run",
	].map((key, index) => [key, index]),
);

/** Orders role grants by content, agents and administration, with destructive actions last. */
export const getGrantablePermissionRegistry = (config: AccessConfig) => {
	const groupOrder = (key: string) =>
		permissionGroupOrder.get(key.split(":")[0] ?? key) ??
		permissionGroupOrder.size;
	const actionOrder = (key: string) =>
		key.endsWith(":delete")
			? permissionActionOrder.size + 1
			: (permissionActionOrder.get(key.split(":").at(-1) ?? key) ??
				permissionActionOrder.size);

	return getPermissionRegistry(config)
		.map((group) => ({
			...group,
			permissions: group.permissions.toSorted(
				(a, b) => actionOrder(a.key) - actionOrder(b.key),
			),
		}))
		.sort((a, b) => groupOrder(a.key) - groupOrder(b.key));
};

/** Flattens the permission registry into keys for role validation and sync. */
export const getValidPermissions = (config: AccessConfig): string[] => {
	return getPermissionRegistry(config).flatMap((group) =>
		group.permissions.map((permission) => permission.key),
	);
};

/** Verifies that a permission exists in the current internal catalogue. */
export const isRegisteredPermission = (
	config: AccessConfig,
	permission: string,
): permission is Permission => {
	return getValidPermissions(config).includes(permission);
};
