import type { Config } from "../../types/config.js";
import { getCapabilityRegistry } from "./capabilities.js";
import { Permissions } from "./definitions.js";
import type { Permission, PermissionGroup, StaticPermission } from "./types.js";

export const corePermissionKeys = Object.values(
	Permissions,
) as StaticPermission[];

const collectionPermissionRegex =
	/^documents:[a-z0-9-_]+:(read|create|update|delete|restore|publish|review)$/;

/** Checks whether a permission is owned and generated by Lucid. */
export const isCorePermission = (
	permission: string,
): permission is Permission => {
	return (
		corePermissionKeys.includes(permission as StaticPermission) ||
		collectionPermissionRegex.test(permission)
	);
};

/** Builds the internal and collection-generated permission catalogue. */
export const getPermissionRegistry = (
	config?: Pick<Config, "collections">,
): PermissionGroup[] => {
	return getCapabilityRegistry(config)
		.map(
			(group): PermissionGroup => ({
				key: group.key,
				details: group.details,
				core: group.core,
				permissions: group.capabilities
					.filter((capability) => capability.permission !== undefined)
					.map((capability) => ({
						key: capability.permission as Permission,
						details: capability.details,
						core: capability.core,
					})),
			}),
		)
		.filter((group) => group.permissions.length > 0);
};

/** Builds the permission catalogue shown in role management. */
export const getGrantablePermissionRegistry = (
	config?: Pick<Config, "collections">,
) => getPermissionRegistry(config);

/** Flattens the permission registry into keys for role validation and sync. */
export const getValidPermissions = (
	config?: Pick<Config, "collections">,
): Permission[] => {
	return getPermissionRegistry(config).flatMap((group) =>
		group.permissions.map((permission) => permission.key),
	);
};

/** Verifies that a permission exists in the current internal catalogue. */
export const isRegisteredPermission = (
	config: Pick<Config, "collections">,
	permission: string,
): permission is Permission => {
	return getValidPermissions(config).includes(permission as Permission);
};
