import { type AccessConfig, getCapabilityRegistry } from "./capabilities.js";
import { Permissions } from "./definitions.js";
import type {
	CorePermission,
	Permission,
	PermissionGroup,
	StaticPermission,
} from "./types.js";

export const corePermissionKeys = Object.values(
	Permissions,
) as StaticPermission[];

const collectionPermissionRegex =
	/^documents:[a-z0-9-_]+:(read|create|update|delete|restore|publish|review)$/;
const agentPermissionRegex = /^agents:[a-z0-9-]+:(use|manage)$/;

/** Checks whether a permission is owned and generated by Lucid. */
export const isCorePermission = (
	permission: string,
): permission is CorePermission => {
	return (
		corePermissionKeys.some((key) => key === permission) ||
		collectionPermissionRegex.test(permission) ||
		agentPermissionRegex.test(permission)
	);
};

/** Builds the core, collection and custom permission catalogue. */
export const getPermissionRegistry = (
	config: AccessConfig,
): PermissionGroup[] => {
	return getCapabilityRegistry(config)
		.map(
			(group): PermissionGroup => ({
				key: group.key,
				details: group.details,
				core: group.core,
				permissions: group.capabilities.flatMap((capability) =>
					capability.permission === undefined
						? []
						: [
								{
									key: capability.permission,
									details: capability.details,
									core: capability.core,
								},
							],
				),
			}),
		)
		.filter((group) => group.permissions.length > 0);
};

/** Builds the permission catalogue shown in role management. */
export const getGrantablePermissionRegistry = (config: AccessConfig) =>
	getPermissionRegistry(config);

/** Flattens the permission registry into keys for role validation and sync. */
export const getValidPermissions = (config: AccessConfig): string[] => {
	return getPermissionRegistry(config).flatMap((group) =>
		group.permissions.map((permission) => permission.key),
	);
};

/** Verifies that a permission exists in the current internal catalogue. */
export const isRegisteredPermission = (
	config: AccessConfig,
	permission: string,
): permission is Permission => {
	return getValidPermissions(config).includes(permission);
};
