import emailConstants from "./emails.js";

export default Object.freeze({
	locales: ["en"] as const,
	openAPIDocsRoute: "/lucid/documentation",
	urls: {
		localhost: "http://localhost:6543",
	},
	headers: {
		csrf: "X-CSRF-Token",
		idempotencyKey: "idempotency-key",
		interfaceLocale: "Lucid-Locale",
		requestId: "X-Request-Id",
		tenant: "X-Lucid-Tenant",
	},
	cookies: {
		csrf: "_csrf",
		refreshToken: "_refresh",
		accessToken: "_access",
	},
	jwt: {
		algorithm: "HS256" as const,
	},
	scrypt: {
		N: 2 ** 16, // 65536 iterations
		r: 8,
		p: 1,
		dkLen: 32,
	},
	fieldBuiler: {
		maxRepeaterDepth: 3,
	},
	collectionBuilder: {
		locked: false,
		revisions: false,
		localized: false,
		autoSave: false,
		scheduling: false,
		orderable: false,
		protectedEnvironments: ["latest", "revision", "snapshot"],
		revisionRetentionDays: 30,
		previewExpirationSeconds: 3600,
		previewMaxExpirationSeconds: 604_800,
		publishing: {
			allowSelfApproval: false,
			comments: {
				request: "required" as const,
				decision: "optional" as const,
			},
			snapshotVersionType: "snapshot" as const,
			workflow: {
				stageColors: [
					"grey",
					"red",
					"yellow",
					"green",
					"blue",
					"purple",
				] as const,
				color: "grey" as const,
			},
		},
	},
	customFields: {
		link: {
			targets: ["_self", "_blank", "_parent", "_top", "framename"],
		},
		code: {
			languages: [
				"text",
				"javascript",
				"typescript",
				"jsx",
				"tsx",
				"json",
				"html",
				"css",
				"scss",
				"markdown",
				"yaml",
				"bash",
				"sql",
			],
		},
	},
	query: {
		page: 1,
		perPage: 10,
	},
	email: emailConstants,
	i18n: {
		renderedOutput: "i18n-translations.json",
	},
	alerts: {
		storage: {
			type: "storage" as const,
			thresholds: [
				{ percent: 80, level: "warning", cooldownDays: 7 },
				{ percent: 90, level: "warning", cooldownDays: 3 },
				{ percent: 100, level: "critical", cooldownDays: 1 },
			] as const,
		},
		publishRequest: {
			type: "publish-request" as const,
		},
	},
	errors: {
		name: "Error",
		message: "An error occurred",
		status: 500,
		code: undefined,
		errors: undefined,
	},
	rateLimit: {
		ttlBufferSeconds: 1,
		scopes: {
			sensitive: { limit: 10, scopeKey: "sensitive" },
			low: { limit: 20, scopeKey: "low" },
			standard: { limit: 60, scopeKey: "standard" },
			stream: { limit: 500, scopeKey: "stream" },
		},
	},
	directories: {
		public: "public",
		lucid: ".lucid",
		base: "lucid",
		viteBuild: "spa",
		plugins: "plugins",
	},
	typeGeneration: {
		file: "types.d.ts",
		files: {
			core: "types.d.ts",
			client: "client.d.ts",
		},
		disclaimer:
			"/** This file is generated as a part of the Lucid CMS build process. Do not edit this file manually. */",
		modules: {
			coreTypes: "@lucidcms/core/types",
			clientTypes: "@lucidcms/client/types",
			publicTypes: "@lucidcms/types",
		} as const,
	},
	brickTypes: {
		builder: "builder",
		fixed: "fixed",
	} as const,
	db: {
		prefix: "lucid_",
		nameSeparator: "__",
		generatedColumnPrefix: "_" as const,
		generatedIndexPrefix: "lucid_idx__" as const,
		customFieldTablePrefix: "cf_" as const,
		//* postgres max table name length is 63 bytes
		minTableNameByteLimit: 63,
		//* max length for collection, brick keys. With the above and database adapter max table name length, we can ensure the table name is not too long
		//* This is the max size given table structure "lucid_document__{collection-key:16}__${brick-key:16}__{rep/usr/doc/med}_hash"
		maxBuilderKeyLength: 16,
		//* core migrations use a zero-padded numeric prefix which always sorts before a
		//* 13 digit timestamp, so external migrations can never clash and always run after core
		externalMigrationNameRegex: /^\d{13}-[a-z0-9][a-z0-9-_]*$/,
		//* project relative directory external migrations are automatically loaded from
		externalMigrationDirectory: "migrations" as const,
	},
	logScopes: {
		lucid: "lucid",
		migrations: "migrations",
		cron: "cron",
		config: "config",
		sync: "sync",
		query: "query",
		http: "http",
		validation: "validation",
		typeGeneration: "type-generation",
		kvAdapter: "kv-adapter",
		queueAdapter: "queue-adapter",
		imageProcessor: "image-processor",
		mediaAdapter: "media-adapter",
		emailAdapter: "email-adapter",
		oidcAuth: "oidc-auth",
		ai: "ai",
	} as const,
	retention: 30,
	cronSchedules: {
		maintenance: "0 0 * * *",
		scheduledPublishing: "0 */4 * * *",
	},
	csrfExpiration: 604800, // 7 days in seconds
	refreshTokenExpiration: 604800, // 7 days in seconds
	accessTokenExpiration: 300, // 5 minutes in seconds
	authCacheExpiration: 60, // 1 minute in seconds
	passwordResetTokenExpirationMinutes: 15, // 15 minutes
	userInviteTokenExpirationMinutes: 1440, // 24 hours in minutes
	emailChangeTokenExpirationMinutes: 1440, // 24 hours in minutes
	presignedUrlExpiration: 3600000, // 1 hour in ms
	uploadSessionExpiration: 3600000, // 1 hour in ms
	uploadSessionPartSize: 8 * 1024 * 1024, // 8MiB
	shareLinkExpiration: 86400, // 24 hours in seconds
	documentation:
		"https://lucidjs.build/en/cms/docs/configuration/configuring-lucid-cms/",
	mediaAwaitingSyncInterval: 3600000, // 1 hour in ms
	media: {
		imagePresetQuality: 80,
		processedKey: "processed" as const,
		awaitingSyncKey: "awaiting-sync" as const,
		visibilityKeys: {
			private: "private",
			public: "public",
		} as const,
		reservedTenantKeys: [
			"processed",
			"awaiting-sync",
			"private",
			"public",
		] as const,
		previewableTypes: ["image", "video", "audio"] as const,
	},
	license: {
		statusRecheckIntervalSeconds: 3600, // 1 hour
	},
	endpoints: {
		lucidRemoteApiDomain: "https://api.lucidcms.io",
	},
	config: {
		filename: "lucid.config",
		extensions: [".ts", ".js", ".mjs", ".mts"],
	},
	defaultUploadDirectory: "uploads",
	queue: {
		maxAttempts: 3,
		concurrentLimit: 5,
		batchSize: 10,
	},
	userTokens: {
		passwordReset: "password_reset",
		refresh: "refresh",
		invitation: "invitation",
		emailChangeConfirm: "email_change_confirm",
		emailChangeRevert: "email_change_revert",
	} as const,
	refreshTokenRevokeReasons: {
		logout: "logout",
		rotated: "rotated",
		revokeAll: "revoke_all",
		reuseDetected: "reuse_detected",
		accountRevokeAll: "account_revoke_all",
		adminRevokeAll: "admin_revoke_all",
		emailChangeReverted: "email_change_reverted",
	} as const,
	userTokenRevokeReasons: {
		passwordResetUsed: "password_reset_used",
		invitationAccepted: "invitation_accepted",
		invitationResent: "invitation_resent",
		emailChangeConfirmed: "email_change_confirmed",
		emailChangeCancelled: "email_change_cancelled",
		emailChangeReverted: "email_change_reverted",
		emailChangeSuperseded: "email_change_superseded",
		expired: "expired",
	} as const,
	emailChangeRequestStatuses: {
		pending: "pending",
		confirmed: "confirmed",
		cancelled: "cancelled",
		reverted: "reverted",
		superseded: "superseded",
	} as const,
	securityAudit: {
		actions: {
			emailChange: "email_change",
			passwordChange: "password_change",
			roleChange: "role_change",
			authProviderUnlink: "auth_provider_unlink",
		},
		redactedValue: "[REDACTED]",
	} as const,
	authState: {
		actionTypes: {
			invitation: "invitation",
			authLink: "authenticated-link",
			login: "login",
		} as const,
		defaultRedirectPath: "/lucid",
		defaultErrorRedirectPath: "/lucid/login",
		ttl: 600000,
	},
});
