import { PermissionGroups } from "../libs/permission/definitions.js";
import T from "../translations/index.js";

export default Object.freeze({
	locales: ["en"] as const,
	openAPIDocsRoute: "/lucid/documentation",
	headers: {
		csrf: "X-CSRF-Token",
		contentLocale: "lucid-content-locale",
	},
	cookies: {
		csrf: "_csrf",
		refreshToken: "_refresh",
		accessToken: "_access",
	},
	scrypt: {
		N: 2 ** 16, // 65536 iterations
		r: 8,
		p: 1,
		dkLen: 32,
	},
	seedDefaults: {
		roles: [
			{
				name: "Admin",
				description: "The admin role has permissions to do everything.",
				permissions: [
					...PermissionGroups.users.permissions,
					...PermissionGroups.roles.permissions,
					...PermissionGroups.media.permissions,
					...PermissionGroups.emails.permissions,
					...PermissionGroups.jobs.permissions,
					...PermissionGroups.content.permissions,
					...PermissionGroups["client-integrations"].permissions,
					...PermissionGroups.settings.permissions,
				],
			},
			{
				name: "Editor",
				description: "The editor role has permissions to manage content.",
				permissions: [
					...PermissionGroups.media.permissions,
					...PermissionGroups.content.permissions,
				],
			},
		],
	},
	fieldBuiler: {
		maxRepeaterDepth: 3,
	},
	collectionBuilder: {
		isLocked: false,
		useRevisions: false,
		useTranslations: false,
		useAutoSave: false,
		protectedEnvironments: ["latest", "revision"],
		revisionRetentionDays: 30,
	},
	customFields: {
		link: {
			targets: ["_self", "_blank", "_parent", "_top", "framename"],
		},
	},
	query: {
		page: 1,
		perPage: 10,
	},
	locations: {
		resetPassword: "/lucid/reset-password",
		acceptInvitation: "/lucid/accept-invitation",
	},
	assets: {
		emailLogo: "/lucid/assets/email-logo.svg",
	},
	errors: {
		name: T("default_error_name"),
		message: T("default_error_message"),
		status: 500,
		code: undefined,
		errors: undefined,
	},
	emailTemplates: {
		resetPassword: "reset-password",
		userInvite: "user-invite",
		passwordResetSuccess: "password-reset-success",
		emailChanged: "email-changed",
	},
	emailRenderedOutput: "email-templates.json",
	rateLimit: {
		ttlBufferSeconds: 1,
		scopes: {
			sensitive: { limit: 10, scopeKey: "sensitive" },
			low: { limit: 20, scopeKey: "low" },
			standard: { limit: 60, scopeKey: "standard" },
			stream: { limit: 500, scopeKey: "stream" },
		},
	},
	directories: {
		public: "public",
		lucid: ".lucid",
		base: "lucid",
		viteBuild: "spa",
		plugins: "plugins",
	},
	typeGeneration: {
		file: "types.d.ts",
		disclaimer:
			"/** This file is generated as a part of the Lucid CMS build process. Do not edit this file manually. */",
		modules: {
			coreTypes: "@lucidcms/core/types",
		} as const,
	},
	brickTypes: {
		builder: "builder",
		fixed: "fixed",
	} as const,
	db: {
		prefix: "lucid_",
		collectionKeysJoin: "__",
		generatedColumnPrefix: "_" as const,
	},
	logScopes: {
		lucid: "lucid",
		migrations: "migrations",
		cron: "cron",
		config: "config",
		sync: "sync",
		query: "query",
		http: "http",
		validation: "validation",
		typeGeneration: "type-generation",
		kvAdapter: "kv-adapter",
		queueAdapter: "queue-adapter",
		imageProcessor: "image-processor",
		mediaAdapter: "media-adapter",
		emailAdapter: "email-adapter",
		oidcAuth: "oidc-auth",
	} as const,
	retention: 30,
	cronSchedule: "0 0 * * *",
	csrfExpiration: 604800, // 7 days in seconds
	refreshTokenExpiration: 604800, // 7 days in seconds
	accessTokenExpiration: 300, // 5 minutes in seconds
	passwordResetTokenExpirationMinutes: 15, // 15 minutes
	userInviteTokenExpirationMinutes: 1440, // 24 hours in minutes
	presignedUrlExpiration: 3600000, // 1 hour in ms
	shareLinkExpiration: 86400, // 24 hours in seconds
	documentation:
		"https://lucidjs.build/en/cms/docs/configuration/configuring-lucid-cms/",
	mediaAwaitingSyncInterval: 3600000, // 1 hour in ms
	media: {
		imagePresetQuality: 80,
		processedKey: "processed" as const,
		visibilityKeys: {
			private: "private",
			public: "public",
		} as const,
	},
	license: {
		statusRecheckIntervalSeconds: 21600, //  6 hours
	},
	endpoints: {
		licenseVerify: "https://api.lucidjs.build/v1/cms-license/verify",
	},
	config: {
		filename: "lucid.config",
		extensions: [".ts", ".js", ".mjs", ".mts"],
	},
	defaultUploadDirectory: "uploads",
	queue: {
		maxAttempts: 3,
		concurrentLimit: 5,
		batchSize: 10,
	},
	userTokens: {
		passwordReset: "password_reset",
		refresh: "refresh",
		invitation: "invitation",
	} as const,
	authState: {
		actionTypes: {
			invitation: "invitation",
			authLink: "authenticated-link",
			login: "login",
		} as const,
		defaultRedirectPath: "/lucid",
		defaultErrorRedirectPath: "/lucid/login",
		ttl: 600000,
	},
});
