export { default as authenticate } from "./libs/fastify/middleware/authenticate.js";
export { default as clientAuthentication } from "./libs/fastify/middleware/client-authenticate.js";
export { default as contentLocale } from "./libs/fastify/middleware/content-locale.js";
export { default as logRoute } from "./libs/fastify/middleware/log-route.js";
export { default as validateCSRF } from "./libs/fastify/middleware/validate-csrf.js";
export { default as validateBody } from "./libs/fastify/middleware/validate-body.js";
export { default as validateParams } from "./libs/fastify/middleware/validate-params.js";
export { default as validateQuery } from "./libs/fastify/middleware/validate-query.js";
export { default as permissions } from "./libs/fastify/middleware/permissions.js";
