import crypto from "node:crypto";
import { INTERNAL_SIGNED_URL_EXPIRY_MS } from "../constants.js";

type SignedMediaQuery = Record<string, string | number | undefined>;

type CreateSignedMediaUrlParams = {
	host: string;
	path: string;
	key: string;
	secretKey: string;
	query?: SignedMediaQuery;
};

type CreateSignedMediaTokenParams = {
	path: string;
	key: string;
	timestamp: string | number;
	secretKey: string;
	query?: SignedMediaQuery;
};

type ValidateSignedMediaUrlParams = CreateSignedMediaTokenParams & {
	token: string;
};

const normalizeQuery = (query?: SignedMediaQuery) =>
	Object.fromEntries(
		Object.entries(query ?? {})
			.filter(([, value]) => value !== undefined)
			.sort(([left], [right]) => left.localeCompare(right))
			.map(([key, value]) => [key, String(value)]),
	);

const serializeQuery = (query?: SignedMediaQuery) =>
	new URLSearchParams(normalizeQuery(query)).toString();

/**
 * Creates the HMAC token used by the plugin-owned upload/download routes.
 * The route path and signed query are included so tokens cannot be replayed
 * across different operations.
 */
export const createSignedMediaToken = (
	params: CreateSignedMediaTokenParams,
): string => {
	return crypto
		.createHmac("sha256", params.secretKey)
		.update(
			[
				params.path,
				params.key,
				String(params.timestamp),
				serializeQuery(params.query),
			].join("\n"),
		)
		.digest("hex");
};

/**
 * Builds a Lucid-owned signed media URL for binding-backed uploads/downloads.
 * This is intentionally not an R2 presigned URL because the browser cannot
 * access the Worker binding directly.
 */
export const createSignedMediaUrl = (
	params: CreateSignedMediaUrlParams,
): string => {
	const timestamp = Date.now();
	const query = normalizeQuery(params.query);
	const token = createSignedMediaToken({
		path: params.path,
		key: params.key,
		timestamp,
		secretKey: params.secretKey,
		query,
	});

	const search = new URLSearchParams({
		key: params.key,
		token,
		timestamp: String(timestamp),
		...query,
	});

	const host = params.host.endsWith("/")
		? params.host.slice(0, -1)
		: params.host;
	const path = params.path.startsWith("/") ? params.path : `/${params.path}`;

	return `${host}/lucid/api/v1${path}?${search.toString()}`;
};

/**
 * Validates a signed media URL generated by this plugin and enforces its TTL.
 * Matching on path and query keeps upload and download tokens scoped to the
 * exact internal route they were created for.
 */
export const validateSignedMediaUrl = (
	params: ValidateSignedMediaUrlParams,
): boolean => {
	const timestamp = Number.parseInt(String(params.timestamp), 10);
	if (!Number.isFinite(timestamp)) {
		return false;
	}

	const age = Date.now() - timestamp;
	if (age < 0 || age > INTERNAL_SIGNED_URL_EXPIRY_MS) {
		return false;
	}

	const expectedToken = createSignedMediaToken({
		path: params.path,
		key: params.key,
		timestamp,
		secretKey: params.secretKey,
		query: params.query,
	});

	if (params.token.length !== expectedToken.length) {
		return false;
	}

	return crypto.timingSafeEqual(
		Buffer.from(params.token),
		Buffer.from(expectedToken),
	);
};
