export const ADAPTER_KEY = "cloudflare";
export const LUCID_VERSION = "0.x.x";
export const DEFAULT_KV_BINDING = "LUCID_KV";
export const DEFAULT_R2_BINDING = "LUCID_MEDIA_BUCKET";
export const DEFAULT_QUEUE_BINDING = "LUCID_QUEUE";
export const DEFAULT_D1_BINDING = "LUCID_D1";
/** Latest Cloudflare compatibility date validated against this runtime. */
export const DEFAULT_COMPATIBILITY_DATE = "2026-06-30";

export default {
	CONFIG_FILE: "lucid.config.js",
	ENTRY_FILE: "server",
	WORKER_EXPORT_ARTIFACT_TYPE: "cloudflare:worker-export",
	WRANGLER_CONFIG_ARTIFACT_TYPE: "cloudflare:wrangler",
	WRANGLER_DEV_CONFIG_FILE: "wrangler.lucid.jsonc",
	WRANGLER_BUILD_CONFIG_FILE: "wrangler.jsonc",
	WRANGLER_DEPLOY_CONFIG_FILE: ".wrangler/deploy/config.json",
	WRANGLER_GENERATED_CONFIG_MARKER:
		"Generated by Lucid CMS. Do not edit directly.",
	ASSETS_BINDING: "ASSETS",
	DEFAULT_CRONS: ["0 0 * * *", "0 */4 * * *"],
} as const;
