export const Permissions = {
	UsersRead: "users:read",
	UsersCreate: "users:create",
	UsersUpdate: "users:update",
	UsersDelete: "users:delete",
	RolesRead: "roles:read",
	RolesCreate: "roles:create",
	RolesUpdate: "roles:update",
	RolesDelete: "roles:delete",
	MediaRead: "media:read",
	MediaCreate: "media:create",
	MediaUpdate: "media:update",
	MediaDelete: "media:delete",
	EmailRead: "email:read",
	EmailSend: "email:send",
	EmailDelete: "email:delete",
	JobsRead: "jobs:read",
	DocumentsRead: "documents:read",
	DocumentsCreate: "documents:create",
	DocumentsUpdate: "documents:update",
	DocumentsDelete: "documents:delete",
	DocumentsRestore: "documents:restore",
	DocumentsPublish: "documents:publish",
	IntegrationsRead: "integrations:read",
	IntegrationsCreate: "integrations:create",
	IntegrationsUpdate: "integrations:update",
	IntegrationsDelete: "integrations:delete",
	IntegrationsRegenerate: "integrations:regenerate",
	LicenseUpdate: "license:update",
	CacheClear: "cache:clear",
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];
