/**
 * Internal browser module generated by adminExtensionsPlugin in ../build/extensions/plugin.ts.
 * In dev and production builds, Vite resolves this ID to generated JavaScript based
 * on the host's resolved config.admin. It exports route and slot registrations with
 * Solid lazy components backed by literal import() paths, so Vite can compile and
 * split those modules without importing components in the server config.
 * This declaration describes those exports for TypeScript; it creates no runtime code.
 */
declare module "virtual:lucid-admin" {
	export const routes: Array<{
		key: string;
		path: string;
		component: import("./types/route.js").AdminRouteComponent;
		navigation?: import("./types/navigation.js").AdminRouteNavigation;
	}>;
	export const brickSlots: Array<{
		key: string;
		slot: import("../components/BrickSlots/types.js").BrickSlot;
		match: import("../components/BrickSlots/types.js").BrickSlotMatch;
		component: import("../components/BrickSlots/types.js").BrickSlotComponent;
	}>;
	export const fieldSlots: Array<{
		key: string;
		slot: import("../components/FieldSlots/types.js").FieldSlot;
		match: import("../components/FieldSlots/types.js").FieldSlotMatch;
		component: import("../components/FieldSlots/types.js").FieldSlotComponent;
	}>;
}

/**
 * Generated by the same plugin and imported once by the SPA entry point for its
 * side effects. Imports local scripts and stylesheets; HTTPS assets are added to
 * the HTML by the plugin instead. This module has no exports.
 */
declare module "virtual:lucid-admin-assets" {}
