export const PLUGIN_KEY = "cloudflare-r2";
export const ADAPTER_KEY = "cloudflare-r2";
export const LUCID_VERSION = "0.x.x";
export const SUPPORTED_RUNTIME_ADAPTER_KEY = "cloudflare";
export const DEFAULT_MAX_UPLOAD_SIZE = 100 * 1024 * 1024; // 100MB
export const PRESIGNED_URL_EXPIRY = 3600; // 1 hour
export const INTERNAL_SIGNED_URL_EXPIRY_MS = PRESIGNED_URL_EXPIRY * 1000;
export const STORAGE_UPLOAD_PATH = "media/r2/storage/upload";
export const STORAGE_DOWNLOAD_PATH = "media/r2/storage/download";
export const STORAGE_UPLOAD_ROUTE = `/lucid/api/v1/${STORAGE_UPLOAD_PATH}`;
export const STORAGE_DOWNLOAD_ROUTE = `/lucid/api/v1/${STORAGE_DOWNLOAD_PATH}`;
export const STORAGE_RATE_LIMIT = 20;
export const STORAGE_RATE_LIMIT_WINDOW_MS = 60 * 1000;
